[pytest]
pythonpath = src
testpaths = tests
markers =
	integration: integration-level tests
	slow: slower-running tests
filterwarnings =
	ignore:`clean_up_tokenization_spaces` was not set.*:FutureWarning
